server:
  port: 8888

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wcggit/spring-cloud-demo-config