server:
  port: 8080
  group: order
  zkAddress: 192.168.99.100:2181

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://192.168.99.100:6603/test1?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123
    cloud:
            stream:
                  instanceCount: 1
                  instanceIndex: 0
                  kafka:
                    binder:
                      brokers: 192.168.99.100:9092
                      zkNodes: ${server.zkAddress}
                      offsetUpdateTimeWindow: 10000
                      #offsetUpdateCount: 0
                      requiredAcks: 1
                      minPartitionCount: 1
                      replicationFactor: 1
                    bindings:
                      input:
                        group: ${server.group}
                        consumer:
                          autoCommitOffset: true
                          startOffset: earliest
                          headerMode: raw
                      output:
                        group: ${server.group}
                        producer:
                          bufferSize: 16384
                          sync: true
                          batchTimeout: 0
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
logging:
#    level.org.mybatis: DEBUG
#    level.com.ibatis: DEBUG
#    level.com.jfk.mapper: DEBUG
#    level.org.springframework: DEBUG
#    level.com.netflix: DEBUG
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
#    registryFetchIntervalSeconds: 40 #抓取节点的时间
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  histrix:
    enabled: false

hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false
